info:
  contact: {}
paths:
  /ping:
    get:
      description: This endpoint will hit the server
      produces:
      - application/json
      responses:
        "200":
          description: PONG!
          schema:
            type: string
      summary: Health Check
      tags:
      - Server
swagger: "2.0"