version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-dev
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=epayment
    volumes:
      - db_data:/var/lib/mysql
    restart: always

volumes:
  db_data: